config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#home'

  resources :races do
    resources :stats, only: [:show]
  end

  get '/past_races/:id' => 'races#past_races', as: 'past_races'
  get '/my_past_races' => 'races#my_past_races', as: 'my_past_races'

  # resources :locations
  resources :user_prs
  resources :stats, only: [:edit, :update]
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :stats
  has_many :users, through: :stats
  validates :name, presence: true #, uniqueness: true
  validates :distance, presence: true
  validates :location, presence: true
  validates :event_date, presence: true
  # before_validation :remove_empty_string

  def current_stat(current_user)
    self.stats.where(user: current_user).first
  end

  def self.remove_empty_string
    self.where("location <> ''") || self.where("name <> ''") || self.where("distance <> ''")
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
    @user = current_user
    @races = current_user.races
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @races, status: 201}
    end
  end

  def show
    @user = current_user
    # @races = current_user.races
    @race = current_user.races.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @race, status: 201}
    end
  end

  def past_races
    @race = current_user.races.find_by(id: params[:id])
    @race.stats[0].completion = true
    @race.stats[0].save

    redirect_to my_past_races_path, notice: "Your race was successfully moved to Past Races!"
  end

  def my_past_races(past_races)
    @race = current_user.races.find_by(id: params[:id])
    @race.stats[0].completion = true
    
    respond_to do |f|
      f.html {render my_past_races}
      f.json {render json: @race, status: 201}
    end
  end

  def new
    @race = current_user.races.build
    # @race = Race.new
  end

  def edit
    @race = current_user.races.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :edit}
      f.json {render json: @pr, status: 201}
    end
  end

  def create
    @race = current_user.races.build(race_params)
    if @race.save
      @race.users << current_user
      respond_to do |f|
        f.html {redirect_to races_path, notice: "Your race was saved!"}
        f.json {render json: @race, status: 201}
      end
    else
      flash[:alert] = "Your race did not save. Please try again."
      render :new
    end
  end

  def update
    @race = current_user.races.find_by(id: params[:id])
    @race.update(race_params)
      if @race.save
        redirect_to races_path, notice: "Your race was updated!"
      else
        redirect_to edit_race_path, alert: "Your race did not update. Please try again."
      end
  end

  def destroy
    @race = current_user.races.find_by(id: params[:id])
    @race.destroy
      redirect_to races_path, notice: "Your race was deleted."
  end

  private

  def race_params
    params.require(:race).permit(:name, :distance, :event_date, :location, :finish_time)
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for race do |f| %>
<div class="">
  <div class="row">
    <%# f.label :name, "Race Name" %>
  </div>

  <div class="row">
      <%= f.text_field :name, :class => "new-race", :placeholder => (race.errors.full_messages_for(:name).first || "Enter a new race name")%>
      <%# f.collection_select :name, Race.remove_empty_string.order(:name), :name, :name, include_blank: true %>
  </div>

  <div class="">
    <div class="row">
      <%# f.label :distance, "Distance" %>
    </div>
  </div>

  <div class="row">
      <%= f.text_field :distance, :class => "new-race", :placeholder => (race.errors.full_messages_for(:distance).first || "Enter the distance") %>
      <%# f.collection_select :distance, Race.remove_empty_string.order(:distance), :distance, :distance, include_blank: true %>
  </div>

  <div class="">
    <div class="row">
      <%# f.label :location, "Location" %>
    </div>
  </div>

  <div class="row">
      <%= f.text_field :location, :class => "new-race", :placeholder => (race.errors.full_messages_for(:location).first || "Enter the location") %>
      <%# f.collection_select :location, Race.remove_empty_string.order(:location), :location, :location, include_blank: true %>
  </div>


  <div class="">
    <div class="row">
      <%# f.label :event_date, "Date" %>
    </div>
  </div>

  <div class="row">
      <%= f.date_field :event_date, :class => "new-race", :placeholder => (race.errors.full_messages_for(:event_date).first) %>
  </div>

  <div class="row buttons">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/races/edit.html.erb
<h1>Edit Your Race</h1>
<%= render partial: 'form', locals: {race: @race} %>

app/views/races/index.html.erb
<h1><%= current_user.first_name %>'s Races</h1>

  <h6>*NEW* Click on a race to see who else will be running!</h6><br>

  <% current_user.race_incomplete.each do |race| %>

<div id="view-race-users-div">
  <li><strong><button id="view-race-users" type="button" name="button"><%= race.name %></button><%# link_to race.name, races_path(race) %></strong> - <%= race.distance %> - <%= race.location %> - <%= race.event_date %> > <%= link_to "Edit Race", edit_race_path(race) %> > <%= link_to "Delete Race", race_path(race), method: :delete, data: { confirm: "Are you sure you want to delete this race?" } %> > <%= link_to "Mark Race Complete", race_stat_path(race, race.current_stat(current_user)) %></li>
  <% end %>
</div>

app/views/races/my_past_races.html.erb
<h1><%= current_user.first_name %>'s Past Races</h1>
<% current_user.race_complete.each do |race| %>

<li><%= race.name %> - <%= race.distance %> - <%= race.location %> - <%= race.event_date %> > <%= link_to "Delete Race", race_path(race), method: :delete, data: { confirm: "Are you sure you want to delete this race?" }%></li>
<% end %>

app/views/races/new.html.erb
<h1>Add a New Race!</h1>
<%= render partial: 'form', locals: {race: @race} %>

app/views/races/show.html.erb
<h1><%= @race %></h1>