config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#home'

  resources :races do
    resources :stats, only: [:show]
  end

  get '/past_races/:id' => 'races#past_races', as: 'past_races'
  get '/my_past_races' => 'races#my_past_races', as: 'my_past_races'

  # resources :locations
  resources :user_prs
  resources :stats, only: [:edit, :update]
end

app/models/user_pr.rb
class UserPr < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/controllers/user_prs_controller.rb
class UserPrsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @user = current_user
    @prs = current_user.user_prs
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @prs, status: 201}
    end
  end

  def show
    @user = current_user
    @pr = current_user.user_prs.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @pr, status: 201}
    end
  end

  def new
    @pr = current_user.user_prs.build
  end

  def edit
    @pr = current_user.user_prs.find_by(id: params[:id])
    respond_to do |f|
      f.html {render :edit}
      f.json {render json: @pr, status: 201}
    end
  end

  def create
    @pr = current_user.user_prs.build(user_pr_params)
    if @pr.save
      respond_to do |f|
        f.html {redirect_to user_prs_path, notice: "Your PR was saved!"}
        f.json {render json: @pr, status: 201}
      end
    else
      redirect_to new_user_pr_path, alert: "Your PR did not save. Please try again."
    end
  end

  def update
    @pr = current_user.user_prs.find_by(id: params[:id])
    if @pr.user_id == current_user.id
      @pr.update(user_pr_params)
      if @pr.save
        redirect_to user_prs_path, notice: "Your PR was updated!"
      else
        redirect_to edit_user_pr_path, alert: "Your PR did not update. Please try again."
      end
    else
      redirect_to user_prs_path, alert: "You are not authorized to edit this PR."
    end
  end

  def destroy
    @pr = current_user.user_prs.find_by(id: params[:id])
    if @pr.user_id == current_user.id
      @pr.destroy
      redirect_to user_prs_path, notice: "Your PR was deleted."
    else
      redirect_to user_prs_path, notice: "You are not authorized to delete this PR."
    end
  end

  private

  def user_pr_params
    params.require(:user_pr).permit(:name, :description)
  end
end

app/helpers/user_prs_helper.rb
module UserPrsHelper
end

app/views/user_prs/_form.html.erb
<%= form_for pr do |f| %>
<div id="new-pr-form">
  <div class="">
    <%# f.label :name, "PR" %>
  </div>

  <div class="user-prs">
      <%= f.text_field :name, :class => "new-user-pr-name", :placeholder => (pr.errors.full_messages_for(:name).first || "Enter your PR") %>
  </div>

  <div class="">
    <div class="row">
      <%# f.label :description, "Description" %>
    </div>
  </div>

  <div class="user-prs">
      <%= f.text_area :description, :class => "new-user-pr-description", :placeholder => "Brag about your PR here! Ex. Where/when did this happen? Did anyone else see it happen? Can you still walk?" %>
  </div>

  <div class="row buttons">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/user_prs/edit.html.erb
<h1>Edit a PR!</h1>
<%= render partial: 'form', locals: {pr: @pr} %>

app/views/user_prs/index.html.erb
<h1><%= current_user.first_name %>'s PRs</h1>
<% current_user.user_prs.each do |pr| %>
<li><%= pr.name %> - <%= pr.description %> > <%= link_to "Edit PR", edit_user_pr_path(pr) %> > <%= link_to "Delete PR", user_pr_path(pr), method: :delete, data: { confirm: "Are you sure you want to delete this PR?" } %></li>
<% end %>

app/views/user_prs/new.html.erb
<h1>Create a PR!</h1>
<%= render partial: 'form', locals: {pr: @pr} %>