config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'application#home'

  resources :races do
    resources :stats, only: [:show]
  end

  get '/past_races/:id' => 'races#past_races', as: 'past_races'
  get '/my_past_races' => 'races#my_past_races', as: 'my_past_races'

  # resources :locations
  resources :user_prs
  resources :stats, only: [:edit, :update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title></title>
  </head>
  <body>

  </body>
</html>
  <% if user_signed_in? %>
    <h2>Hello, <%= current_user.first_name%>!</h2>

<!-- add date? -->
<p>What do you want to do?</p>

      <!-- add a PR  -->
  <div id="new-pr-div" class="">
    <button id="new-pr" type="button" name="button" value="add-pr">ADD NEW PR</button>
      <div id="pr-form"></div>
      <!-- <div class="dashboard row">
        <div class="btn btn-md btn-primary buttons">
          <%# link_to "Add a PR", new_user_pr_path %>
        </div>
      </div> -->
  </div><br>
<!-- view PRs  -->
<div class="dashboard row">
  <button id="view-prs" type="button" name="button" value="view-prs" onclick="hideViewPrsText()">VIEW PRs</button>
    <div id="view-prs-div" class=""></div>
  <!-- <div class="btn btn-md btn-primary buttons">
    <%# link_to "View Your PRs", user_prs_path %>
  </div> -->
</div><br>

<!-- view upcoming races  -->
<div class="dashboard row">
  <div class="btn btn-md btn-primary buttons">
    <%= link_to "View Upcoming Races", races_path %>
  </div>
</div><br>

<!-- add an upcoming race  -->
<div id="new-race-div" class="">
  <button id="new-race" type="button" name="button" value="add-race">ADD NEW RACE</button>
    <div id="race-form"></div>
<!-- <div class=" row">
  <div class="btn btn-md btn-primary buttons">
    <%# link_to "Add an Upcoming Race", new_race_path %>
  </div> -->
</div><br>

<!-- view past races  -->
<div class="dashboard row">
  <div class="btn btn-md btn-primary buttons">
    <%= link_to "View Past Races", my_past_races_path %>
  </div>
</div>
<% end%>